CREATE TABLE message(
id INT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
title VARCHAR(120) NOT NULL DEFAULT '',
content VARCHAR(255) NOT NULL DEFAULT '',
created_at INT NOT NULL DEFAULT 0,
user_name VARCHAR(32) NOT NULL DEFAULT '',
KEY message_user_name(user_name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
