<?php
/**
 * Created by PhpStorm.
 * User: v_shipmao
 * Date: 2018/3/5
 * Time: 18:03
 */

namespace app\lib\exception;


use think\Exception;
use think\exception\Handle;

class ExceptionHandler extends Handle
{
    public function render(Exception $e)
    {
        return(json('~ ~~~~~~~~~~~~~~~~~~'));
        //return parent::render($e); // TODO: Change the autogenerated stub
    }
}